// ⛔ This file is auto-generated, please don't edit it
export * from "discord.js"
export * from "./app/pagination"
export * from "./app/database"
export * from "./app/handler"
export * from "./app/logger"
export * from "./app/core"
export * from "./namespaces/data"
export * from "./namespaces/utils"
export * from "./namespaces/docs"

export * as Discord from "discord.js"
export * as pagination from "./app/pagination"
export * as database from "./app/database"
export * as handler from "./app/handler"
export * as logger from "./app/logger"
export * as core from "./app/core"
export * as data from "./namespaces/data"
export * as utils from "./namespaces/utils"
export * as docs from "./namespaces/docs"
